language: node_js
sudo: false
node_js:
  - "11.4.0"

cache: yarn

install:
  - yarn install

script:
  # CHECK STYLE
  # - yarn run lint

  # BUILD STAGE
  - yarn run symlink-ci
  - yarn run build:demo
  # TEST STAGE
  #- yarn run test
